packages:
  - 'packages/*/*'
# Require a package to be published at least 12 days (17280 minutes) before it can be installed
# minimumReleaseAge: 17280
minimumReleaseAgeExclude:
  - '@kong/*'
  - '@kong-ui/*'
  - '@kong-ui-public/*'
# When set to no-downgrade, pnpm will fail if a package's trust level has decreased compared to previous releases
trustPolicy: no-downgrade
# Ignore policy if published at least 12 days (17280 minutes)
trustPolicyIgnoreAfter: 17280

auditConfig:
  ignoreGhsas:
    - 'GHSA-p9ff-h696-f583'
    - 'GHSA-5xrq-8626-4rwp'
    - 'GHSA-gv7w-rqvm-qjhr'
    - 'GHSA-fx2h-pf6j-xcff'

overrides:
  form-data@>=3.0.0 <3.0.4: '>=4.0.6'
  fast-uri@<=3.1.1: '>=4.0.0'
  minimatch@>=9.0.0 <9.0.7: '>=10.2.5'
  serialize-javascript@<=7.0.2: '>=7.0.5'
  dompurify@<3.2.4: '>=3.4.11'
  picomatch@<2.3.2: '>=4.0.4'
  picomatch@>=4.0.0 <4.0.4: '>=4.0.4'
  handlebars@>=4.0.0 <=4.7.8: '>=4.7.9'
  path-to-regexp@<0.1.13: '>=8.4.2'
  lodash-es@<=4.17.23: '>=4.18.0'
  lodash@<=4.17.23: '>=4.18.0'
  axios@<1.15.0: '>=1.18.0'
  tmp@<0.2.6: '>=0.2.7'
  shell-quote@>=1.1.0 <=1.8.3: '>=1.8.4'
  ws@>=8.0.0 <8.21.0: '>=8.21.0'
  undici@>=7.0.0 <7.28.0: '>=7.28.0 <8.0.0'
  linkify-it@<=5.0.0: '>=5.0.1'
  sigstore@<=4.1.0: '>=4.1.1'

onlyBuiltDependencies:
  - '@evilmartians/lefthook'
  - '@parcel/watcher'
  - '@swc/core'
  - 'core-js'
  - 'core-js-pure'
  - 'cypress'
  - 'es5-ext'
  - 'esbuild'
  - 'swagger-ui'
  - 'tree-sitter'
  - 'tree-sitter-json'
  - 'tree-sitter-yaml'
  - 'vue-demi'
