packages:
  - 'packages/*/*'
catalog:
  vue: ^3.5.13
  'vue-router': ^4.4.5
  axios: ^1.11.0
  pinia: ">= 2.1.7 < 3"
  '@kong/icons': ^1.33.2
  '@kong/design-tokens': 1.17.4
  '@kong/kongponents': ^9.34.2
