packages:
  - 'packages/*/*'
# Require a package to be published at least 12 days (17280 minutes) before it can be installed
# minimumReleaseAge: 17280
minimumReleaseAgeExclude:
  - '@kong/*'
  - '@kong-ui/*'
  - '@kong-ui-public/*'
# When set to no-downgrade, pnpm will fail if a package's trust level has decreased compared to previous releases
trustPolicy: no-downgrade
# Ignore policy if published at least 12 days (17280 minutes)
trustPolicyIgnoreAfter: 17280

auditConfig:
  ignoreGhsas:
    - 'GHSA-p9ff-h696-f583'
    - 'GHSA-5xrq-8626-4rwp'
    - 'GHSA-gv7w-rqvm-qjhr'
    - 'GHSA-fx2h-pf6j-xcff'

overrides:
  form-data@>=3.0.0 <3.0.4: '>=4.0.6'
  fast-uri@<4.1.2: '>=4.1.2'
  minimatch@>=9.0.0 <9.0.7: '>=10.2.6'
  serialize-javascript@<=7.0.2: '>=7.1.0'
  dompurify@<3.2.4: '>=3.4.13'
  picomatch@<2.3.2: '>=4.0.5'
  picomatch@>=4.0.0 <4.0.4: '>=4.0.5'
  handlebars@>=4.0.0 <=4.7.8: '>=4.7.9'
  path-to-regexp@<0.1.13: '>=8.4.2'
  lodash-es@<=4.17.23: '>=4.18.0'
  lodash@<=4.17.23: '>=4.18.0'
  axios@<1.15.0: '>=1.19.0'
  tmp@<0.2.6: '>=0.2.7'
  shell-quote@>=1.1.0 <=1.8.3: '>=1.10.0'
  ws@>=8.0.0 <8.21.0: '>=8.21.3'
  undici@>=7.0.0 <7.29.0: '>=7.29.0 <8.0.0'
  linkify-it@<=5.0.0: '>=6.1.0'
  sigstore@<=4.1.0: '>=5.0.0'
  js-yaml@>=3.0.0 <3.15.1: '>=5.2.3'
  js-yaml@>=4.0.0 <4.3.1: '>=5.2.3'
  nx@>=20.8.0 <22.7.7: '>=22.7.8'
  tar@<=7.5.18: '>=7.5.22'
  brace-expansion@<5.0.9: '>=5.0.9'
  '@eslint/config-array@<0.23.5': '>=0.23.5 <1.0.0'
  immutable@>=5.0.0-beta.1 <5.1.8: '>=5.1.9'
  immutable@<4.3.9: '>=4.3.9 <6.0.0'
  ip-address@<=10.3.0: '>=10.5.0'
  pacote@>=11.2.7 <21.5.1: '>=21.5.1'

onlyBuiltDependencies:
  - '@evilmartians/lefthook'
  - '@parcel/watcher'
  - '@swc/core'
  - 'core-js'
  - 'core-js-pure'
  - 'cypress'
  - 'es5-ext'
  - 'esbuild'
  - 'swagger-ui'
  - 'tree-sitter'
  - 'tree-sitter-json'
  - 'tree-sitter-yaml'
  - 'vue-demi'
