export const RLASchema = {
  fields: [
    {
      'default': 'rate-limiting-advanced',
      'type': 'input',
      'inputType': 'hidden',
      'styleClasses': 'd-none hidden-field',
      'pinned': true,
      'id': 'name',
      'model': 'name',
      'label': '',
      'order': 0,
    },
    {
      'type': 'switch',
      'model': 'enabled',
      'label': 'Enabled',
      'textOn': 'This plugin is Enabled',
      'textOff': 'This plugin is Disabled',
      'styleClasses': 'field-switch hide-label',
      'default': true,
      'pinned': true,
      'id': 'enabled',
      'order': 0,
    },
    {
      'type': 'selectionGroup',
      'disabled': false,
      'inputType': 'hidden',
      'styleClasses': 'hide-label',
      'fields': [
        {
          'label': 'Global',
          'description': 'All services, routes, and consumers',
        },
        {
          'label': 'Scoped',
          'description': 'Specific Gateway Services, Routes, Consumers, and/or Consumer Groups',
          'fields': [
            {
              'id': 'service-id',
              'model': 'service-id',
              'label': 'Gateway Service',
              'placeholder': 'Select a Gateway Service',
              'type': 'AutoSuggest',
              'entity': 'services',
              'inputValues': {
                'fields': [
                  'name',
                  'id',
                ],
              },
              'help': 'The Gateway Service to which this plugin configuration will apply',
              'disabled': false,
            },
            {
              'id': 'route-id',
              'model': 'route-id',
              'label': 'Route',
              'placeholder': 'Select a Route',
              'type': 'AutoSuggest',
              'entity': 'routes',
              'inputValues': {
                'fields': [
                  'name',
                  'id',
                ],
                'primaryField': 'id',
              },
              'help': 'The Route that this Plugin configuration will target',
              'disabled': false,
            },
            {
              'model': 'consumer-id',
              'label': 'Consumer',
              'placeholder': 'Select a Consumer',
              'type': 'AutoSuggest',
              'entity': 'consumers',
              'inputValues': {
                'fields': [
                  'username',
                  'custom_id',
                  'id',
                ],
                'primaryField': 'username',
              },
              'help': 'The Consumer that this plugin configuration will target',
              'disabled': false,
            },
            {
              'model': 'consumer_group-id',
              'label': 'Consumer Group',
              'placeholder': 'Select a Consumer Group',
              'type': 'AutoSuggest',
              'entity': 'consumer_groups',
              'entityDataKey': 'consumer_group',
              'inputValues': {
                'fields': [
                  'name',
                  'id',
                ],
                'primaryField': 'name',
              },
              'help': 'The Consumer Group that this plugin configuration will target',
              'disabled': false,
            },
          ],
        },
      ],
      'pinned': true,
      'id': 'selectionGroup',
      'model': 'selectionGroup',
      'label': '',
      'order': 0,
    },
    {
      'id': 'protocols',
      'default': [
        'grpc',
        'grpcs',
        'http',
        'https',
      ],
      'help': 'A list of the request protocols that will trigger this plugin. The default value, as well as the possible values allowed on this field, may change depending on the plugin type.',
      'label': 'Protocols',
      'required': true,
      'styleClasses': 'plugin-protocols-select',
      'type': 'multiselect',
      'values': [
        {
          'label': 'grpc',
          'value': 'grpc',
        },
        {
          'label': 'grpcs',
          'value': 'grpcs',
        },
        {
          'label': 'http',
          'value': 'http',
        },
        {
          'label': 'https',
          'value': 'https',
        },
      ],
      'placeholder': 'Select valid protocols for the plugin. Default protocols: grpc, grpcs, http, https',
      'model': 'protocols',
      'order': 0,
    },
    {
      'default': '',
      'type': 'input',
      'label': 'Instance Name',
      'inputType': 'text',
      'help': 'A custom name for this plugin instance to help identifying from the list view.',
      'id': 'instance_name',
      'model': 'instance_name',
      'order': 0,
    },
    {
      'label': 'Tags',
      'name': 'tags',
      'type': 'input',
      'inputType': 'text',
      'valueType': 'array',
      'valueArrayType': 'string',
      'placeholder': 'Enter list of tags',
      'help': 'An optional set of strings for grouping and filtering, separated by commas.',
      'hint': 'e.g. tag1, tag2, tag3',
      'id': 'tags',
      'model': 'tags',
      'order': 0,
    },
    {
      'id': 'config-compound_identifier',
      'model': 'config-compound_identifier',
      'type': 'input',
      'label': 'Config.Compound Identifier',
      'help': '<p>Similar to <code>identifer</code>, but supports combining multiple items. The priority of <code>compound_identifier</code> is higher than <code>identifier</code>, which means if <code>compound_identifer</code> is set, it will be used, otherwise <code>identifier</code> will be used.</p>\n',
      'elements': {
        'one_of': [
          'ip',
          'credential',
          'consumer',
          'service',
          'header',
          'path',
          'consumer-group',
        ],
        'type': 'string',
      },
      'valueArrayType': 'string',
      'inputType': 'text',
      'valueType': 'array',
      'order': 0,
    },
    {
      'help': '<p>List of consumer groups allowed to override the rate limiting settings for the given Route or Service. Required if <code>enforce_consumer_groups</code> is set to <code>true</code>.</p>\n',
      'label': 'Config.Consumer Groups',
      'hint': 'e.g. group1, group2',
      'type': 'input',
      'placeholder': 'Enter list of consumer groups',
      'valueArrayType': 'string',
      'inputType': 'text',
      'valueType': 'array',
      'id': 'config-consumer_groups',
      'model': 'config-consumer_groups',
      'order': 0,
    },
    {
      'id': 'config-dictionary_name',
      'model': 'config-dictionary_name',
      'type': 'input',
      'required': true,
      'label': 'Config.Dictionary Name',
      'help': '<p>The shared dictionary where counters are stored. When the plugin is configured to synchronize counter data externally (that is <code>config.strategy</code> is <code>cluster</code> or <code>redis</code> and <code>config.sync_rate</code> isn&#39;t <code>-1</code>), this dictionary serves as a buffer to populate counters in the data store on each synchronization cycle.</p>\n',
      'selectOptions': {
        'hideNoneSelectedText': true,
      },
      'default': 'kong_rate_limiting_counters',
      'placeholder': 'Default: kong_rate_limiting_counters',
      'inputType': 'text',
      'valueType': 'string',
      'order': 0,
    },
    {
      'id': 'config-disable_penalty',
      'model': 'config-disable_penalty',
      'type': 'checkbox',
      'label': 'Config.Disable Penalty',
      'help': '<p>If set to <code>true</code>, this doesn&#39;t count denied requests (status = <code>429</code>). If set to <code>false</code>, all requests, including denied ones, are counted. This parameter only affects the <code>sliding</code> window_type.</p>\n',
      'default': false,
      'valueType': 'boolean',
      'order': 0,
    },
    {
      'id': 'config-enforce_consumer_groups',
      'model': 'config-enforce_consumer_groups',
      'type': 'checkbox',
      'label': 'Config.Enforce Consumer Groups',
      'help': '<p>Determines if consumer groups are allowed to override the rate limiting settings for the given Route or Service. Flipping <code>enforce_consumer_groups</code> from <code>true</code> to <code>false</code> disables the group override, but does not clear the list of consumer groups. You can then flip <code>enforce_consumer_groups</code> to <code>true</code> to re-enforce the groups.</p>\n',
      'default': false,
      'valueType': 'boolean',
      'order': 0,
    },
    {
      'id': 'config-error_code',
      'model': 'config-error_code',
      'type': 'input',
      'label': 'Config.Error Code',
      'help': '<p>Set a custom error code to return when the rate limit is exceeded.</p>\n',
      'default': 429,
      'placeholder': 'Default: 429',
      'inputType': 'number',
      'valueType': 'number',
      'order': 0,
    },
    {
      'id': 'config-error_message',
      'model': 'config-error_message',
      'type': 'input',
      'label': 'Config.Error Message',
      'help': '<p>Set a custom error message to return when the rate limit is exceeded.</p>\n',
      'default': 'API rate limit exceeded',
      'placeholder': 'Default: API rate limit exceeded',
      'inputType': 'text',
      'valueType': 'string',
      'order': 0,
    },
    {
      'id': 'config-header_name',
      'model': 'config-header_name',
      'type': 'input',
      'label': 'Config.Header Name',
      'help': '<p>A string representing an HTTP header name.</p>\n',
      'inputType': 'text',
      'valueType': 'string',
      'order': 0,
    },
    {
      'id': 'config-hide_client_headers',
      'model': 'config-hide_client_headers',
      'type': 'checkbox',
      'label': 'Config.Hide Client Headers',
      'help': '<p>Optionally hide informative response headers that would otherwise provide information about the current status of limits and counters.</p>\n',
      'default': false,
      'valueType': 'boolean',
      'order': 0,
    },
    {
      'id': 'config-identifier',
      'model': 'config-identifier',
      'type': 'select',
      'required': true,
      'label': 'Config.Identifier',
      'help': '<p>The type of identifier used to generate the rate limit key. Defines the scope used to increment the rate limiting counters. Can be <code>ip</code>, <code>credential</code>, <code>consumer</code>, <code>service</code>, <code>header</code>, <code>path</code> or <code>consumer-group</code>.</p>\n',
      'values': [
        'ip',
        'credential',
        'consumer',
        'service',
        'header',
        'path',
        'consumer-group',
      ],
      'selectOptions': {
        'hideNoneSelectedText': true,
      },
      'default': 'consumer',
      'valueType': 'string',
      'order': 0,
    },
    {
      'id': 'config-limit',
      'help': '<p>One or more requests-per-window limits to apply. There must be a matching number of window limits and sizes specified.</p>\n',
      'label': 'Config.Limit',
      'inputAttributes': {
        'class': 'form-control',
        'style': {
          'minWidth': '200px',
        },
        'type': 'number',
      },
      'type': 'array',
      'valueType': 'array',
      'valueArrayType': 'array',
      'itemContainerComponent': 'FieldArrayItem',
      'fieldClasses': 'kong-form-array-field',
      'fieldItemsClasses': 'kong-form-array-field-item',
      'validator': 'array',
      'styleClasses': 'kong-form-field-wrapper',
      'newElementButtonLabel': '+ Add',
      'newElementButtonLabelClasses': 'kong-form-new-element-button-label',
      'required': true,
      'selectOptions': {
        'hideNoneSelectedText': true,
      },
      'model': 'config-limit',
      'order': 0,
    },
    {
      'id': 'config-lock_dictionary_name',
      'model': 'config-lock_dictionary_name',
      'type': 'input',
      'required': true,
      'label': 'Config.Lock Dictionary Name',
      'help': '<p>The shared dictionary where concurrency control locks are stored. The default shared dictionary is <code>kong_locks</code>. The shared dictionary should be declare in nginx-kong.conf.</p>\n',
      'selectOptions': {
        'hideNoneSelectedText': true,
      },
      'default': 'kong_locks',
      'placeholder': 'Default: kong_locks',
      'inputType': 'text',
      'valueType': 'string',
      'order': 0,
    },
    {
      'id': 'config-namespace',
      'model': 'config-namespace',
      'type': 'input',
      'required': true,
      'label': 'Config.Namespace',
      'help': '<p>The rate limiting library namespace to use for this plugin instance. Counter data and sync configuration is isolated in each namespace.</p>\n',
      'selectOptions': {
        'hideNoneSelectedText': true,
      },
      'inputType': 'text',
      'valueType': 'string',
      'order': 0,
    },
    {
      'id': 'config-path',
      'model': 'config-path',
      'type': 'input',
      'label': 'Config.Path',
      'help': '<p>A string representing a URL path, such as /path/to/resource. Must start with a forward slash (/) and must not contain empty segments (i.e., two consecutive forward slashes).</p>\n',
      'inputType': 'text',
      'valueType': 'string',
      'order': 0,
    },
    {
      'id': 'config-redis-cluster_max_redirections',
      'model': 'config-redis-cluster_max_redirections',
      'type': 'input',
      'required': false,
      'label': 'Config.Redis.Cluster Max Redirections',
      'help': '<p>Maximum retry attempts for redirection.</p>\n',
      'default': 5,
      'placeholder': 'Default: 5',
      'inputType': 'number',
      'valueType': 'number',
      'order': 0,
    },
    {
      'id': 'config-redis-cluster_nodes',
      'model': 'config-redis-cluster_nodes',
      'type': 'array',
      'required': false,
      'label': 'Config.Redis.Cluster Nodes',
      'help': '<p>Cluster addresses to use for Redis connections when the <code>redis</code> strategy is defined. Defining this field implies using a Redis Cluster. The minimum length of the array is 1 element.</p>\n',
      'elements': {
        'fields': [
          {
            'ip': {
              'default': '127.0.0.1',
              'description': 'A string representing a host name, such as example.com.',
              'required': true,
              'type': 'string',
            },
          },
          {
            'port': {
              'between': [
                0,
                65535,
              ],
              'default': 6379,
              'description': 'An integer representing a port number between 0 and 65535, inclusive.',
              'type': 'integer',
            },
          },
        ],
        'type': 'record',
      },
      'newElementButtonLabelClasses': 'kong-form-new-element-button-label',
      'fieldClasses': 'array-card-container-wrapper',
      'itemContainerComponent': 'FieldArrayCardContainer',
      'items': {
        'type': 'object',
        'schema': {
          'fields': [
            {
              'id': 'config-redis-cluster_nodes-ip',
              'model': 'ip',
              'type': 'input',
              'required': true,
              'label': 'Ip',
              'help': '<p>A string representing a host name, such as example.com.</p>\n',
              'selectOptions': {
                'hideNoneSelectedText': true,
              },
              'default': '127.0.0.1',
              'placeholder': 'Default: 127.0.0.1',
              'inputType': 'text',
              'valueType': 'string',
            },
            {
              'id': 'config-redis-cluster_nodes-port',
              'model': 'port',
              'type': 'input',
              'label': 'Port',
              'help': '<p>An integer representing a port number between 0 and 65535, inclusive.</p>\n',
              'default': 6379,
              'placeholder': 'Default: 6379',
              'inputType': 'number',
              'valueType': 'number',
            },
          ],
        },
      },
      'nestedFields': true,
      'submitWhenNull': true,
      'valueType': 'array',
      'order': 0,
    },
    {
      'id': 'config-redis-connect_timeout',
      'model': 'config-redis-connect_timeout',
      'type': 'input',
      'label': 'Config.Redis.Connect Timeout',
      'help': '<p>An integer representing a timeout in milliseconds. Must be between 0 and 2^31-2.</p>\n',
      'default': 2000,
      'placeholder': 'Default: 2000',
      'inputType': 'number',
      'valueType': 'number',
      'order': 0,
    },
    {
      'id': 'config-redis-connection_is_proxied',
      'model': 'config-redis-connection_is_proxied',
      'type': 'checkbox',
      'required': false,
      'label': 'Config.Redis.Connection Is Proxied',
      'help': '<p>If the connection to Redis is proxied (e.g. Envoy), set it <code>true</code>. Set the <code>host</code> and <code>port</code> to point to the proxy address.</p>\n',
      'default': false,
      'valueType': 'boolean',
      'order': 0,
    },
    {
      'id': 'config-redis-database',
      'model': 'config-redis-database',
      'type': 'input',
      'label': 'Config.Redis.Database',
      'help': '<p>Database to use for the Redis connection when using the <code>redis</code> strategy</p>\n',
      'default': 0,
      'placeholder': 'Default: 0',
      'inputType': 'number',
      'valueType': 'number',
      'order': 0,
    },
    {
      'id': 'config-redis-host',
      'model': 'config-redis-host',
      'type': 'input',
      'label': 'Config.Redis.Host',
      'help': '<p>A string representing a host name, such as example.com.</p>\n',
      'default': '127.0.0.1',
      'placeholder': 'Default: 127.0.0.1',
      'inputType': 'text',
      'valueType': 'string',
      'order': 0,
    },
    {
      'id': 'config-redis-keepalive_backlog',
      'model': 'config-redis-keepalive_backlog',
      'type': 'input',
      'label': 'Config.Redis.Keepalive Backlog',
      'help': '<p>Limits the total number of opened connections for a pool. If the connection pool is full, connection queues above the limit go into the backlog queue. If the backlog queue is full, subsequent connect operations fail and return <code>nil</code>. Queued operations (subject to set timeouts) resume once the number of connections in the pool is less than <code>keepalive_pool_size</code>. If latency is high or throughput is low, try increasing this value. Empirically, this value is larger than <code>keepalive_pool_size</code>.</p>\n',
      'inputType': 'number',
      'valueType': 'number',
      'order': 0,
    },
    {
      'id': 'config-redis-keepalive_pool_size',
      'model': 'config-redis-keepalive_pool_size',
      'type': 'input',
      'label': 'Config.Redis.Keepalive Pool Size',
      'help': '<p>The size limit for every cosocket connection pool associated with every remote server, per worker process. If neither <code>keepalive_pool_size</code> nor <code>keepalive_backlog</code> is specified, no pool is created. If <code>keepalive_pool_size</code> isn&#39;t specified but <code>keepalive_backlog</code> is specified, then the pool uses the default value. Try to increase (e.g. 512) this value if latency is high or throughput is low.</p>\n',
      'default': 256,
      'placeholder': 'Default: 256',
      'inputType': 'number',
      'valueType': 'number',
      'order': 0,
    },
    {
      'id': 'config-redis-password',
      'model': 'config-redis-password',
      'type': 'input',
      'referenceable': true,
      'label': 'Config.Redis.Password',
      'help': '<p>Password to use for Redis connections. If undefined, no AUTH commands are sent to Redis.</p>\n',
      'inputType': 'password',
      'valueType': 'string',
      'order': 0,
    },
    {
      'id': 'config-redis-port',
      'model': 'config-redis-port',
      'type': 'input',
      'label': 'Config.Redis.Port',
      'help': '<p>An integer representing a port number between 0 and 65535, inclusive.</p>\n',
      'default': 6379,
      'placeholder': 'Default: 6379',
      'inputType': 'number',
      'valueType': 'number',
      'order': 0,
    },
    {
      'id': 'config-redis-read_timeout',
      'model': 'config-redis-read_timeout',
      'type': 'input',
      'label': 'Config.Redis.Read Timeout',
      'help': '<p>An integer representing a timeout in milliseconds. Must be between 0 and 2^31-2.</p>\n',
      'default': 2000,
      'placeholder': 'Default: 2000',
      'inputType': 'number',
      'valueType': 'number',
      'order': 0,
    },
    {
      'id': 'config-redis-redis_proxy_type',
      'model': 'config-redis-redis_proxy_type',
      'type': 'select',
      'required': false,
      'label': 'Config.Redis.Redis Proxy Type',
      'help': '<p>If the <code>connection_is_proxied</code> is enabled, this field indicates the proxy type and version you are using. For example, you can enable this optioin when you want authentication between Kong and Envoy proxy.</p>\n',
      'values': [
        'envoy_v1.31',
      ],
      'selectOptions': {
        'noneSelectedText': 'No selection...',
      },
      'valueType': 'string',
      'order': 0,
    },
    {
      'id': 'config-redis-send_timeout',
      'model': 'config-redis-send_timeout',
      'type': 'input',
      'label': 'Config.Redis.Send Timeout',
      'help': '<p>An integer representing a timeout in milliseconds. Must be between 0 and 2^31-2.</p>\n',
      'default': 2000,
      'placeholder': 'Default: 2000',
      'inputType': 'number',
      'valueType': 'number',
      'order': 0,
    },
    {
      'id': 'config-redis-sentinel_master',
      'model': 'config-redis-sentinel_master',
      'type': 'input',
      'label': 'Config.Redis.Sentinel Master',
      'help': '<p>Sentinel master to use for Redis connections. Defining this value implies using Redis Sentinel.</p>\n',
      'inputType': 'text',
      'valueType': 'string',
      'order': 0,
    },
    {
      'id': 'config-redis-sentinel_nodes',
      'model': 'config-redis-sentinel_nodes',
      'type': 'array',
      'required': false,
      'label': 'Config.Redis.Sentinel Nodes',
      'help': '<p>Sentinel node addresses to use for Redis connections when the <code>redis</code> strategy is defined. Defining this field implies using a Redis Sentinel. The minimum length of the array is 1 element.</p>\n',
      'elements': {
        'fields': [
          {
            'host': {
              'default': '127.0.0.1',
              'description': 'A string representing a host name, such as example.com.',
              'required': true,
              'type': 'string',
            },
          },
          {
            'port': {
              'between': [
                0,
                65535,
              ],
              'default': 6379,
              'description': 'An integer representing a port number between 0 and 65535, inclusive.',
              'type': 'integer',
            },
          },
        ],
        'type': 'record',
      },
      'newElementButtonLabelClasses': 'kong-form-new-element-button-label',
      'fieldClasses': 'array-card-container-wrapper',
      'itemContainerComponent': 'FieldArrayCardContainer',
      'items': {
        'type': 'object',
        'schema': {
          'fields': [
            {
              'id': 'config-redis-sentinel_nodes-host',
              'model': 'host',
              'type': 'input',
              'required': true,
              'label': 'Host',
              'help': '<p>A string representing a host name, such as example.com.</p>\n',
              'selectOptions': {
                'hideNoneSelectedText': true,
              },
              'default': '127.0.0.1',
              'placeholder': 'Default: 127.0.0.1',
              'inputType': 'text',
              'valueType': 'string',
            },
            {
              'id': 'config-redis-sentinel_nodes-port',
              'model': 'port',
              'type': 'input',
              'label': 'Port',
              'help': '<p>An integer representing a port number between 0 and 65535, inclusive.</p>\n',
              'default': 6379,
              'placeholder': 'Default: 6379',
              'inputType': 'number',
              'valueType': 'number',
            },
          ],
        },
      },
      'nestedFields': true,
      'submitWhenNull': true,
      'valueType': 'array',
      'order': 0,
    },
    {
      'id': 'config-redis-sentinel_password',
      'model': 'config-redis-sentinel_password',
      'type': 'input',
      'referenceable': true,
      'label': 'Config.Redis.Sentinel Password',
      'help': '<p>Sentinel password to authenticate with a Redis Sentinel instance. If undefined, no AUTH commands are sent to Redis Sentinels.</p>\n',
      'inputType': 'password',
      'valueType': 'string',
      'order': 0,
    },
    {
      'id': 'config-redis-sentinel_role',
      'model': 'config-redis-sentinel_role',
      'type': 'select',
      'label': 'Config.Redis.Sentinel Role',
      'help': '<p>Sentinel role to use for Redis connections when the <code>redis</code> strategy is defined. Defining this value implies using Redis Sentinel.</p>\n',
      'values': [
        'master',
        'slave',
        'any',
      ],
      'selectOptions': {
        'noneSelectedText': 'No selection...',
      },
      'valueType': 'string',
      'order': 0,
    },
    {
      'id': 'config-redis-sentinel_username',
      'model': 'config-redis-sentinel_username',
      'type': 'input',
      'referenceable': true,
      'label': 'Config.Redis.Sentinel Username',
      'help': '<p>Sentinel username to authenticate with a Redis Sentinel instance. If undefined, ACL authentication won&#39;t be performed. This requires Redis v6.2.0+.</p>\n',
      'inputType': 'text',
      'valueType': 'string',
      'order': 0,
    },
    {
      'id': 'config-redis-server_name',
      'model': 'config-redis-server_name',
      'type': 'input',
      'required': false,
      'label': 'Config.Redis.Server Name',
      'help': '<p>A string representing an SNI (server name indication) value for TLS.</p>\n',
      'inputType': 'text',
      'valueType': 'string',
      'order': 0,
    },
    {
      'id': 'config-redis-ssl',
      'model': 'config-redis-ssl',
      'type': 'checkbox',
      'required': false,
      'label': 'Config.Redis.Ssl',
      'help': '<p>If set to true, uses SSL to connect to Redis.</p>\n',
      'default': false,
      'valueType': 'boolean',
      'order': 0,
    },
    {
      'id': 'config-redis-ssl_verify',
      'model': 'config-redis-ssl_verify',
      'type': 'checkbox',
      'required': false,
      'label': 'Config.Redis.Ssl Verify',
      'help': '<p>If set to true, verifies the validity of the server SSL certificate. If setting this parameter, also configure <code>lua_ssl_trusted_certificate</code> in <code>kong.conf</code> to specify the CA (or server) certificate used by your Redis server. You may also need to configure <code>lua_ssl_verify_depth</code> accordingly.</p>\n',
      'default': false,
      'valueType': 'boolean',
      'order': 0,
    },
    {
      'id': 'config-redis-username',
      'model': 'config-redis-username',
      'type': 'input',
      'referenceable': true,
      'label': 'Config.Redis.Username',
      'help': '<p>Username to use for Redis connections. If undefined, ACL authentication won&#39;t be performed. This requires Redis v6.0.0+. To be compatible with Redis v5.x.y, you can set it to <code>default</code>.</p>\n',
      'inputType': 'text',
      'valueType': 'string',
      'order': 0,
    },
    {
      'id': 'config-retry_after_jitter_max',
      'model': 'config-retry_after_jitter_max',
      'type': 'input',
      'label': 'Config.Retry After Jitter Max',
      'help': '<p>The upper bound of a jitter (random delay) in seconds to be added to the <code>Retry-After</code> header of denied requests (status = <code>429</code>) in order to prevent all the clients from coming back at the same time. The lower bound of the jitter is <code>0</code>; in this case, the <code>Retry-After</code> header is equal to the <code>RateLimit-Reset</code> header.</p>\n',
      'default': 0,
      'placeholder': 'Default: 0',
      'inputType': 'number',
      'valueType': 'number',
      'order': 0,
    },
    {
      'help': '<p>The rate-limiting strategy to use for retrieving and incrementing the limits. Available values are: <code>local</code> and <code>cluster</code>.</p>\n',
      'label': 'Config.Strategy',
      'values': [
        'local',
        'redis',
      ],
      'type': 'select',
      'default': 'redis',
      'required': true,
      'selectOptions': {
        'hideNoneSelectedText': true,
      },
      'valueType': 'string',
      'id': 'config-strategy',
      'model': 'config-strategy',
      'order': 0,
    },
    {
      'id': 'config-sync_rate',
      'model': 'config-sync_rate',
      'type': 'input',
      'label': 'Config.Sync Rate',
      'help': '<p>How often to sync counter data to the central data store. A value of 0 results in synchronous behavior; a value of -1 ignores sync behavior entirely and only stores counters in node memory. A value greater than 0 will sync the counters in the specified number of seconds. The minimum allowed interval is 0.02 seconds (20ms).</p>\n',
      'inputType': 'number',
      'valueType': 'number',
      'order': 0,
    },
    {
      'id': 'config-window_size',
      'help': '<p>One or more window sizes to apply a limit to (defined in seconds). There must be a matching number of window limits and sizes specified.</p>\n',
      'label': 'Config.Window Size',
      'inputAttributes': {
        'class': 'form-control',
        'style': {
          'minWidth': '200px',
        },
        'type': 'number',
      },
      'type': 'array',
      'valueType': 'array',
      'valueArrayType': 'array',
      'itemContainerComponent': 'FieldArrayItem',
      'fieldClasses': 'kong-form-array-field',
      'fieldItemsClasses': 'kong-form-array-field-item',
      'validator': 'array',
      'styleClasses': 'kong-form-field-wrapper',
      'newElementButtonLabel': '+ Add',
      'newElementButtonLabelClasses': 'kong-form-new-element-button-label',
      'required': true,
      'selectOptions': {
        'hideNoneSelectedText': true,
      },
      'model': 'config-window_size',
      'order': 0,
    },
    {
      'id': 'config-window_type',
      'model': 'config-window_type',
      'type': 'select',
      'label': 'Config.Window Type',
      'help': '<p>Sets the time window type to either <code>sliding</code> (default) or <code>fixed</code>. Sliding windows apply the rate limiting logic while taking into account previous hit rates (from the window that immediately precedes the current) using a dynamic weight. Fixed windows consist of buckets that are statically assigned to a definitive time range, each request is mapped to only one fixed window based on its timestamp and will affect only that window&#39;s counters.</p>\n',
      'values': [
        'sliding',
        'fixed',
      ],
      'selectOptions': {
        'noneSelectedText': 'No selection...',
      },
      'default': 'sliding',
      'valueType': 'string',
      'order': 0,
    },
  ],
  _supported_redis_partial_type: 'redis-ee',
}

export const RLAModel = {
  'name': 'rate-limiting-advanced',
  'enabled': true,
  'service-id': null,
  'route-id': null,
  'consumer-id': null,
  'consumer_group-id': null,
  'protocols': [
    'grpc',
    'grpcs',
    'http',
    'https',
  ],
  'instance_name': '',
  'tags': null,
  'config-compound_identifier': null,
  'config-consumer_groups': null,
  'config-dictionary_name': 'kong_rate_limiting_counters',
  'config-disable_penalty': false,
  'config-enforce_consumer_groups': false,
  'config-error_code': 429,
  'config-error_message': 'API rate limit exceeded',
  'config-header_name': null,
  'config-hide_client_headers': false,
  'config-identifier': 'consumer',
  'config-limit': null,
  'config-lock_dictionary_name': 'kong_locks',
  'config-namespace': null,
  'config-path': null,
  'config-redis-cluster_max_redirections': 5,
  'config-redis-cluster_nodes': null,
  'config-redis-connect_timeout': 2000,
  'config-redis-connection_is_proxied': false,
  'config-redis-database': 0,
  'config-redis-host': '127.0.0.1',
  'config-redis-keepalive_backlog': null,
  'config-redis-keepalive_pool_size': 256,
  'config-redis-password': null,
  'config-redis-port': 6379,
  'config-redis-read_timeout': 2000,
  'config-redis-redis_proxy_type': null,
  'config-redis-send_timeout': 2000,
  'config-redis-sentinel_master': null,
  'config-redis-sentinel_nodes': null,
  'config-redis-sentinel_password': null,
  'config-redis-sentinel_role': null,
  'config-redis-sentinel_username': null,
  'config-redis-server_name': null,
  'config-redis-ssl': false,
  'config-redis-ssl_verify': false,
  'config-redis-username': null,
  'config-retry_after_jitter_max': 0,
  'config-strategy': 'redis',
  'config-sync_rate': null,
  'config-window_size': null,
  'config-window_type': 'sliding',
}
