export default {
  fields: [{
    inputType: 'text',
    label: 'Config.Scopes Claim',
    model: 'config-scopes_claim',
    type: 'input',
  }, {
    inputType: 'text',
    label: 'Config.Scopes Required',
    model: 'config-scopes_required',
    type: 'input',
  }, {
    inputType: 'text',
    label: 'Config.Audience Claim',
    model: 'config-audience_claim',
    type: 'input',
  }, {
    inputType: 'text',
    label: 'Config.Audience Required',
    model: 'config-audience_required',
    type: 'input',
  }, {
    inputType: 'text',
    label: 'Config.Roles Claim',
    model: 'config-roles_claim',
    type: 'input',
  }, {
    inputType: 'text',
    label: 'Config.Roles Required',
    model: 'config-roles_required',
    type: 'input',
  }, {
    inputType: 'text',
    label: 'Config.Groups Claim',
    model: 'config-groups_claim',
    type: 'array',
    valueType: 'string',
    valueArrayType: 'array',
    itemContainerComponent: 'FieldArrayItem',
    fieldClasses: 'w-100',
    fieldItemsClasses: 'd-flex mt-2 w-90',
    inputAttributes: { class: 'form-control', style: { minWidth: '200px' } },
    validator: 'array',
    styleClasses: 'w-100',
    newElementButtonLabel: '+ Add',
  }, {
    inputType: 'text',
    label: 'Config.Groups Required',
    model: 'config-groups_required',
    type: 'array',
    valueType: 'string',
    valueArrayType: 'array',
    itemContainerComponent: 'FieldArrayItem',
    fieldClasses: 'w-100',
    fieldItemsClasses: 'd-flex mt-2 w-90',
    inputAttributes: { class: 'form-control', style: { minWidth: '200px' } },
    validator: 'array',
    styleClasses: 'w-100',
    newElementButtonLabel: '+ Add',
  }, {
    inputType: 'text',
    label: 'Config.Authenticated Groups Claim',
    model: 'config-authenticated_groups_claim',
    type: 'array',
    valueType: 'string',
    valueArrayType: 'array',
    itemContainerComponent: 'FieldArrayItem',
    fieldClasses: 'w-100',
    fieldItemsClasses: 'd-flex mt-2 w-90',
    inputAttributes: { class: 'form-control', style: { minWidth: '200px' } },
    validator: 'array',
    styleClasses: 'w-100',
    newElementButtonLabel: '+ Add',
  }],
}
