name: Add assignee to PRs
on:
  pull_request:
    types: [ opened, reopened ]
permissions:
  pull-requests: write
jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@52939d5d7e273559b3c7b3e04eb46efca3829820
