name: Add assignee to PRs
on:
  pull_request:
    types: [ opened, reopened ]
permissions:
  pull-requests: write
jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - uses: Kong/auto-author-assign@7dbebfbadd984a53a3092c634ae3f8054ed4f81d
