name: PR on close
on:
  pull_request:
    types: ['closed']

jobs:
  unpublish:
    name: remove previews comments for PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Remove preview consumption comment
        uses: Kong/sticky-pull-request-comment@ae583cebedbfd32256b349cce8ddf5772e77636e # v3.0.4
        with:
          header: pr_preview_consumption
          delete: true
          GITHUB_TOKEN: ${{ secrets.KONGPONENTS_BOT_PAT }}

